services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: solutech_user
      POSTGRES_PASSWORD: solutech_password
      POSTGRES_DB: solutech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U solutech_user -d solutech_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_cache:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  next_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next_app
    ports:
      - "3000:3000"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://solutech_user:solutech_password@postgres_db:5432/solutech_db?schema=public
      - REDIS_URL=redis://redis_cache:6379
      - COOKIE_SECURE=false

volumes:
  postgres_data:
